### PR TITLE
Generic bits strategy

### PR DESCRIPTION
**Pull request by yo96**
A small PR that adds a generic bits strategy for hypothesis testing.

### CODE REVIEW

**Comment by jsn1993** [comment]
hmm did you sync up with Peitian on this? He seems to have his own Bits strategy for the closed-loop thingy

**Comment by yo96** [comment]
It's kind of different. His data strategy takes in a dut and automatically generate inputs for that component, whereas this is just a simple strategy that returns a bits object based on nbits argument.

**Comment by ptpan** [comment]
My strategies are for ports and interfaces for different IR data types: `Vector`, `Struct`, and `PackedArray`. The bits strategy is similar to `Vector` so I can implement the Vector strategy using the bits strategy.

**Comment by yo96** [comment]
what do you think of the naming? is `bits_strat` ok?

**Comment by ptpan** [comment]
> what do you think of the naming? is `bits_strat` ok?

I kinda like `bits` over `bits_strat` because hypothesis's built-in strategies have names like `booleans`, `binary`, `decimals`. What do you think?

**Comment by yo96** [comment]
from pymtl3.datatypes import strategies as st
st.bits(4).example()

**Comment by yo96** [comment]
@cbatten any suggestions for naming?

**Comment by cbatten** [comment]
we should ask Zac what he thinks on slack?

**Comment by cbatten** [comment]
@Zac-HD what are your thoughts on how to name and organize our own bits strategy?

**Comment by Zac-HD** [comment]
General advice is to pick a convention, document it for users, use it in all your own code and code samples, and stick to it.

If you want to use the same convention as Hypothesis itself - which I would suggest, since it doesn't sound like you have a firm alternative:

- Name the strategy `bits`
- Put all custom strategies with the same dependencies into a single module named `strategies` (not necessarily `datatypes.strategies`)
- Import the module, not the function, with a meaningful prefix.  For example `import hypothesis.extra.numpy as npst` or `import pymtl3.strategies as pmst`

If you have multiple distinct strategies that you'd want to call `bits`, this requires some more care.

**Pull request merged**
